### ISSUE TITLE
Track_visit throwing error

### ISSUE THREAD

**Issue by cyzanfar** [ankane/ahoy#182] opened 2016-06-05 01:04 UTC
I'm getting a `NoMethodError (undefined method `visitor_id=' for #<Visit:0x007fb1e3a3b5c8>)` when tracking visits.

```
    def track_visit(options, &block)
      binding.pry
      visit =
        visit_model.new do |v|
          v.id = ahoy.visit_id
          v.visitor_id = ahoy.visitor_id # here is the issue
          v.user = user if v.respond_to?(:user=)
          v.started_at = options[:started_at]
        end

      set_visit_properties(visit)

      yield(visit) if block_given?

      begin
        visit.save!
        geocode(visit)
      rescue *unique_exception_classes
        # do nothing
      end
    end
```

I followed the readme. Event tracking works but visit doesn't. would you have any clue on what happening?

**Comment by ankane** [comment] 2016-06-21 03:10
Dupe of #183

**Closed by ankane** 2016-06-21 03:10 UTC
