### ISSUE TITLE
Should Ahoy count as new visits when passing utm_ or after a while with cookies off?

### ISSUE THREAD

**Issue by xdmx** [ankane/ahoy#469] opened 2020-12-28 19:22 UTC
Hi, I'm playing with this gem and so far it's working great. For privacy reasons (and to avoid having to add a cookie banner just for this) I'm setting Ahoy to not use cookies. I see that at the moment it generates a visit & visitor using the user agent and the masked ip, but if I try to visit again from a different place (eg. following a link or with utm params) it doesn't seem to be tracking that as a new visit. Is this expected or could it be improved by counting them as new visits instead?

Also, what do you think about adding some kind of expiration (like there is for cookies: 4h / 2yr) when anonymity sets are used? It could help auto expiring them after a while and counting different visits, I think it'd just be a matter of adding the current date (or time with some rounding) to the 2 scopes. That at least won't rely anymore on the ip to change (eg. static ips) or the browser to get upgraded to a different version.

**Comment by sgrosse** [comment] 2021-05-07 08:00
I'm facing the same problems/questions. I'm using ahoy with
```
Ahoy.mask_ips = true
Ahoy.cookies = false
```
It seems, that visits are only counted once per client. I'd expect, that when I revisit the page 24 hours later it would count as a new visit but somehow that's not happening. All events are also associated to my initial visit (3 days ago).

**Comment by sgrosse** [comment] 2021-05-08 10:00
The problem is based on how the visitor token is generated for cookie-less implementation in `visit_anonymity_set`.
As long I'm using the same browser and ip, the token stays the same and never expires in any way.
I did a workaround to be able to track a new visit at least for every new day/date. Therefore I added `Date.today` to `visit_anonymity_set` which should cause generating a new token the very next day:
```
def visit_anonymity_set
  @visit_anonymity_set ||= Digest::UUID.uuid_v5(UUID_NAMESPACE, ["visit", Ahoy.mask_ip(request.remote_ip), request.user_agent, Date.today].join("/"))
end
```
For now it's fine for me but it's not able to use `Ahoy.visit_duration`. I'll try to add something that keeps the token the same for the duration of `Ahoy.visit_duration`. I need to think about it.

**Comment by HereComePretzel** [comment] 2021-05-17 19:15
I've been having similar issues, @sgrosse. Have you had any luck finding a solution?

**Comment by sgrosse** [comment] 2021-05-19 08:35
I think I'm going to add a timestamp at the end of the uuid token.
The timestamp will be something like `Time.now + Ahoy.visit_duration`.
Then I need to add a check, if the token's timestamp is smaller than Time.now and generate a new one if not.
There are some other approaches but I'm concerned about the performance impact by most of them. I want to prevent extra queries e.g. to check the visits `started_at` attribute.
I try to add a PR in the next days. Maybe @ankane has another idea?

**Comment by florianroesler** [comment] 2021-12-16 10:25
I am seeing the same issue with the same configuration as @sgrosse.

Because of the way the anonymity set is created, certain visits never end, e.g. I just found one that had events 1 1/2 years apart. This really unfortunate of course and the quick fix by @sgrosse at least prevents these eternal visits.

Now I am at the same point that the actual `visit_duration` is not taken into account and there is apparently no way around a query to check for an existing visit that started within `Time.now - Ahoy.visit_duration`.

To me, this behavior was completely unexpected when I followed the documentation: https://github.com/ankane/ahoy#gdpr-compliance-1

@ankane Do you have any idea how to get around this? At the very least I think the documentation should reflect this behavior so that no one is surprised.

**Comment by xdmx** [comment] 2022-03-12 15:02
@ankane any thoughts on this? Is it anything you'd like to add/fix in Ahoy?

**Comment by ankane** [comment] 2022-05-20 03:44
Hey all, sorry for the delay.

For UTM parameters, I don't think it's possible with the current design, but could be possible with a change explained below.

For visit expiration, we can add a time component to `visit_anonymity_set`. However, visits across time buckets (for instance, in https://github.com/ankane/ahoy/issues/469#issuecomment-835259810, a user who visits at 11:59 pm and uses the site for a minute) will generate two visits, which isn't great.

One way around this is to query the last two time buckets and use the latest visit from that:

```ruby
Ahoy::Visit.where(visit_token: [current_bucket_token, previous_bucket_token]).order(started_at: :desc).first
```

Another option is to look for an active visit based on the `visitor_token`:

```ruby
Ahoy::Visit.where(visitor_token: ahoy.visitor_token, started_at: Ahoy.visit_duration.ago..).order(started_at: :desc).first
```

I've implemented the 2nd approach in the [anonymity-sets-v2](https://github.com/ankane/ahoy/compare/anonymity-sets-v2) branch (while assigning `visit_token` a value that could be used to switch between approaches).

The 2nd approach is more flexible if the `visit_token` is assigned a random value, since new visits can be generated anytime and it'll pick up the latest one (which could be used for UTM parameters). The downside is it requires a new index to be performant:

```ruby
add_index :ahoy_visits, [:visitor_token, :started_at]
```

@sgrosse If you've implemented something, it'd be great to take a look.

@florianroesler Added a note to the readme in the commit above.

**Comment by borisrorsvort** [comment] 2022-10-12 10:05
@ankane When do you think you’ll merge https://github.com/ankane/ahoy/compare/anonymity-sets-v2 ? 
Also we have the exact same issue regarding visitor duration as the visitor_duration is only used in a cookie based setting.

ps: would def be a good idea to mention this issues in the documentation as a current limitation and add some migration plan doc to your branch.

**Comment by ankane** [comment] 2022-10-19 22:24
@borisrorsvort This will likely be part of Ahoy 5, but I don't have a timeline yet. There's a note in the readme (see the commit above) and will be docs on how to upgrade when it's merged.

**Comment by zealot128** [comment] 2023-03-15 16:20
I've tried the anonymitity-sets-v2 branch,
but I guess, the "time_bucket()" function has the problem that Ankane has mentioned. It will roll over unregarding the started_at of the particular visitor, but always every DURATION.hours.
I guess, the visit_token generation needs to be stateful, somehow lookup ``Ahoy::Visit.where(visitor_token:).maximum(:started_at)`` into the deal and roll over from there.....

For now, I also just add the current date to the hash function, so we at least do not arrive at visits that have couple thousand events, spreading over months. This problem will amplify, when the browser vendors will reduce the information of the [User-Agent string](https://www.chromium.org/updates/ua-reduction/).

**Comment by ankane** [comment] 2023-03-19 01:38
A version of this is now merged if anyone wants to try it. You'll want to add a new index before upgrading.

Active Record

```ruby
add_index :ahoy_visits, [:visitor_token, :started_at]
```

Mongoid

```ruby
class Ahoy::Visit
  index({visitor_token: 1, started_at: -1})
end
```

Also, `Ahoy.cookies = false` will raise an error with a message about adding an index and switching to `Ahoy.cookies = :none` (so users don't miss this important step).

**Comment by borisrorsvort** [comment] 2023-04-25 08:04
@ankane That’s the effect of the index on your new version on master <img width="560" alt="Capture d’écran 2023-04-25 à 10 02 52" src="https://user-images.githubusercontent.com/39081/234213573-4081fefb-bfa0-4cc2-97ba-344260258a46.png">
 🎉

**Comment by morgangrubb** [comment] 2023-09-12 22:45
Because of the way our users bunch up, the 4.x implementation of anonymity sets resulted in ~70% drop in web traffic which is *difficult* to explain to paying customers.

Our solution was to monkey patch the hashing function to include the `session.id`:

```ruby
if Gem.loaded_specs["ahoy_matey"].source.ref != "926cc839"
  raise "ahoy has been updated, check whether or not this monkeypatch is still required."
end

module AhoySessionInVisitorToken
  extend ActiveSupport::Concern

  def visitor_anonymity_set
    @visitor_anonymity_set ||=
      Digest::UUID.uuid_v5(
        Ahoy::Tracker::UUID_NAMESPACE,
        [
          "visitor",
          Ahoy.mask_ip(request.remote_ip),
          request.user_agent,
          request&.session&.id # This line is the difference between this and the original method
        ].compact.join("/")
      )
  end
end

Ahoy::Tracker.prepend(AhoySessionInVisitorToken)
```

It appears that the customisation of the anonymity set hashing function based on the business requirements is a common need, could we add an option to `ahoy` to implement this without monkey patching?

**Comment by ankane** [comment] 2023-10-02 01:33
Hey all, Ahoy 5 is out with this change. Thanks for starting this discussion @xdmx.

**Closed by ankane** 2023-10-02 01:33 UTC
